### ISSUE TITLE
[ci] avoid running most of CI when changing README, docs, etc

### ISSUE THREAD

**Issue by ManifoldFR** [Simple-Robotics/aligator#113]
Right now whenever a PR changes the README or docs, the entire library is being rebuilt by the CI. Maybe we should change that.

**Comment by jcarpent** [comment]
Seems indeed interesting to do and propagate into other libs: eigenpy, hpp-fcl, Pinocchio ;)

**Comment by ManifoldFR** [comment]
Resolved by #115
