### ISSUE TITLE
Pre-commit

### ISSUE THREAD

**Issue by jcarpent** [Simple-Robotics/aligator#116]
Use pre-commit files from other projects (e.g., https://github.com/humanoid-path-planner/hpp-fcl/blob/8bdad1488c1b43d2da27ae2051ab2b1850f2820c/.pre-commit-config.yaml) to automatically update the rules and apply `pre-commit` on PRs.

**Comment by ManifoldFR** [comment]
If I understand:
- integrate the pre-commit bot from https://pre-commit.ci/
- add to the config
  ```
  ci:
    autoupdate_branch: devel
  ```

**Comment by jorisv** [comment]
Hi @jcarpent,

Are you sure to want the pre-commit bot ? I find it really annoying.

1. It pushs some patches on code under development, you can then have conflicts when you push after
2. It doesn't encourage you to use formatting tools on your machine

I prefer a red CI, or to set [autofix_prs](https://pre-commit.ci/#configuration-autofix_prs) to false. Then user can comment "pre-commit.ci autofix" if he really doesn't want to install pre-commit…

**Comment by jorisv** [comment]
Fixed
