### ISSUE TITLE
Bug in finite difference function in tests/python/utils.py 

### ISSUE THREAD

**Issue by edantec** [Simple-Robotics/aligator#127]
## Bug description

The finite difference function in tests/python/utils.py does not integrate correctly the Jacobian transport on Lie manifold. The test of finite differences for MultibodyFreeFwdDynamics is also lacking in Python.  

## Expected behavior

Working unittest for MultibodyFreeFwdDynamics using the finite difference function in tests/python/utils.py.

## Reproduction steps

1. Open unittest tests/python/test_continuous_dynamics.py
2. In function `test_multibody_free()`, add finite difference test for MultibodyFreeFwdDynamics, e.g.:
```
  Jx0 = data.Jx.copy()
  Ju0 = data.Ju.copy()
  Jxdiff, Judiff = finite_diff(ode, space, x0, u0, epsilon)

  assert np.linalg.norm(Jxdiff - Jx0) <= epsilon
  assert np.linalg.norm(Judiff - Ju0) <= epsilon
```
4. Run unittest
5. See error

**Comment by ManifoldFR** [comment]
Is this still a problem ? Or did #128 fix it
