### ISSUE TITLE
pinocchio3 requirement for talos_walk.py example

### ISSUE THREAD

**Issue by m8dotpie** [Simple-Robotics/aligator#140]
## Bug description

Talos walk example requires pinocchio3 while all aligator installations rely on pinocchio2 and I can't find a way to build aligator from sources in the environment with pinocchio3, either built or installed. I have concluded that it relies on p3 based on the usage of `parentJoint` instead of `parent` and `ProximalSettings`

## Expected behavior

Example with talos walk should work. 

## Reproduction steps

1. Run talos_walk.py

## Additional context

Either I don't understand your build pipeline, or some details are missing.

### System

- OS: Ubuntu 22.04

**Comment by ManifoldFR** [comment]
Hi !

Good catch! By building with Pinocchio 3, you mean using the current preview branch?

**Comment by m8dotpie** [comment]
> Hi !
> 
> Good catch! By building with Pinocchio 3, you mean using the current preview branch?

Yes, as far as I know, only preview branch is avaiable publicly for now

**Comment by ManifoldFR** [comment]
> > Hi !
> > Good catch! By building with Pinocchio 3, you mean using the current preview branch?
> 
> Yes, as far as I know, only preview branch is avaiable publicly for now for building from sources (and olivier.roussel::pinocchio for installation from conda)

Oh yes, but unfortunately it's horribly out of date. There's a [recent build on this channel](https://anaconda.org/agm-ws-2023/repo) but it doesn't come with headers that you can use to build aligator against.

I don't think we have a more recent version of Pinocchio 3 with headers available - some of the code contains stuff that's just not public yet (not published as a paper), but we're gearing up for a full public release soon we hope. Until then this example wouldn't actually work, sorry...

**Comment by m8dotpie** [comment]
> > > Hi !
> > > Good catch! By building with Pinocchio 3, you mean using the current preview branch?
> > 
> > 
> > Yes, as far as I know, only preview branch is avaiable publicly for now for building from sources (and olivier.roussel::pinocchio for installation from conda)
> 
> Oh yes, but unfortunately it's horribly out of date. There's a [recent build on this channel](https://anaconda.org/agm-ws-2023/repo) but it doesn't come with headers that you can use to build aligator against.
> 
> I don't think we have a more recent version of Pinocchio 3 with headers available - some of the code contains stuff that's just not public yet (not published as a paper), but we're gearing up for a full public release soon we hope. Until then this example wouldn't actually work, sorry...

Got it, thank you for clarification, looking forward to your publication!
