### ISSUE TITLE
Integrate with SuiteSparse solvers

### ISSUE THREAD

**Issue by ManifoldFR** [Simple-Robotics/aligator#148]
Since https://github.com/conda-forge/suitesparse-feedstock, the latest version (v7.7+) of [SuiteSparse](https://github.com/DrTimothyAldenDavis/SuiteSparse) is available. We may want to add something like CHOLMOD LDLT as a possible backend for the solvers here, using the [Eigen integration](https://eigen.tuxfamily.org/dox/group__CholmodSupport__Module.html).

**Comment by jcarpent** [comment]
Seems to be the way to go for very sparse systems indeed ;)

**Comment by ManifoldFR** [comment]
This will be addressed when **aligator-next** is merged.
