### ISSUE TITLE
Memory leak in the setup function in solver code

### ISSUE THREAD

**Issue by edantec** [Simple-Robotics/aligator#189]
## Bug description

The setup function does not handle workspace and results deletion and thus is leaking memory. 

## Expected behavior

Destroy workspace and results before placement new in solver setup() method.

## Reproduction steps

1. Create a trajectory optimization problem
2. Create a solver object
3. Repeatedly setup the solver with the problem
4. See memory leak

### System

- OS: Ubuntu 20.04
- aligator version: v0.6.1

**Comment by ManifoldFR** [comment]
Thanks for the report @edantec. I forgot to delete the results and workspace instances before doing placement-new.

**Comment by ManifoldFR** [comment]
Closed by #192
