### ISSUE TITLE
Integrate dynamic cast in aligator

### ISSUE THREAD

**Issue by edantec** [Simple-Robotics/aligator#194]
Currently 3 different dynamic casts are needed to access a residual from the vector of stages (for example, to set a reference):
- [x] Casting the CostAbstract held by a stage to a CostStack object
- [x] Casting the component to a composite cost (usually QuadraticResidualCost)
- [x] Casting the underlying residual

We could define template functions (eg: getComponent<T> and getResidual<T>) to access the residual more easily.

**Comment by ManifoldFR** [comment]
PR #199 will take care of your second point @edantec. PR #198 took care of your third point.
