### ISSUE TITLE
Replace vector of CostPtr in CostStack objects by a map of CostPtr

### ISSUE THREAD

**Issue by edantec** [Simple-Robotics/aligator#195]
When creating a CostStack, the user must keep in mind the index of each Cost component they have defined, in order to be able to modify the Cost object later on. It would be more intuitive to use `std::map<String,CostPtr>` to retrieve each component, instead of using `std::vector<CostPtr>`.

**Comment by ManifoldFR** [comment]
We will be using `boost::unordered_map` for now. It is quite fast, faster than `std::unordered_map` in recent versions of Boost (> 1.80)

https://martin.ankerl.com/2022/08/27/hashmap-bench-01/#boost__unordered_map

**Comment by ManifoldFR** [comment]
Two other options are robin_hood maps and unordered_dense from the author the benchmark:
- https://github.com/martinus/robin-hood-hashing
- https://github.com/martinus/unordered_dense
