### ISSUE TITLE
Implementing dynamic cast for CostStack, Integrator and Dynamics

### ISSUE THREAD

**Issue by edantec** [Simple-Robotics/aligator#204]
Following the implementation of dynamic cast for components and residuals, Aligator should manage the templated cast of abstract classes for CostStack, all Integrators and all Dynamics. We should have a function getCostStack() in TrajOptProblem, getIntegrator() in integrator abstract class, and getDynamics() in dynamics abstract class.

**Comment by ManifoldFR** [comment]
Instead of just a shortcut for getting a CostStack from the StageModel, we can do the same as in the previous PR, i.e.

```cpp
// in StageModelTpl

template<typename U> U* getCost() { return dynamic_cast<U*>(&*this->cost_); }
```
