### ISSUE TITLE
Gravity compensation cost uses wrong dimension when computing gradient

### ISSUE THREAD

**Issue by edantec** [Simple-Robotics/aligator#237]
## Bug description

In line https://github.com/Simple-Robotics/aligator/blob/devel/include/aligator/modelling/multibody/gravity-compensation-residual.hxx#L47, we should have
`data.Jx_.leftCols(nv) = -data.gravity_partial_dq_;`
instead of
`data.Jx_.leftCols(nq) = -data.gravity_partial_dq_;`
otherwise the gravity compensation residual does not work for free-flyer robots where nq != nv.

**Comment by ManifoldFR** [comment]
Fixed in 76c0ed0
