### ISSUE TITLE
compile fail, using pixi

### ISSUE THREAD

**Issue by beamiter** [Simple-Robotics/aligator#248]
## Bug description

![image](https://github.com/user-attachments/assets/b2f9778e-448f-40e2-971f-2f927087b536)

## Expected behavior

error "/root/aligator/include/aligator/modelling/multibody/multibody-friction-cone.hxx:11:38: error: expected initializer before '<' token
   11 | void MultibodyFrictionConeResidualTpl<Scalar>::evaluate(const ConstVectorRef &x,
", don't quit know why

## Reproduction steps
1. pull ubuntu:latest docker
2. clone aligator
3. follow the build guidance: pixi run test

1. Load to '...'
4. Click on '....'
5. Scroll down to '....'
6. See error

### Docker image

If this is an installation issue, a Docker image to reproduce it

```dockerfile
...
```
ubuntu:latest

### Code

If this is a runtime issue, provide some minimal code to reproduce it:

```
...
```

### Screenshots

![image](https://github.com/user-attachments/assets/a63553f1-89bc-474b-b156-6f6649516014)

### System
tried many environment, ubuntu 18.04, ubuntu 20.04 and docker "ubuntu:latest", all lead to the same error 

- aligator version: [e.g. 0.1.0]

**Comment by ManifoldFR** [comment]
Hey, thanks for your interest in aligator !

Can you please fill in the rest of the "additional context" section of the issue template ? To answer your question we'll certainly need compilation related info, i.e.
* your operating system (e.g. macOS version or Ubuntu like 22.04...)
* your compiler and compiler version, and where you got your compiler from (e.g. system compiler, brew, conda...)

**Comment by beamiter** [comment]
I suggest trying it in latest ubuntu docker to reproduct the problem

**Comment by jorisv** [comment]
Hello @beamiter,

I can reproduce locally. I will try to fix it.

**Comment by jorisv** [comment]
@beamiter, the `default` environment is broken because right now aligator can't compile without pinocchio (https://github.com/Simple-Robotics/aligator/issues/241)

You can compile using the `all` environment with the following command : `pixi run -e all test`

**Comment by beamiter** [comment]
Thank you for your prompt handling！
